# Generated by Django 3.2 on 2023-02-28 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Men_Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtitle', models.TextField(max_length=300)),
                ('category', models.CharField(choices=[('FORMAL', 'FORMAL'), ('CASUALS', 'CASUALS'), ('SPORTS', 'SPORTS')], max_length=25)),
                ('width', models.CharField(choices=[('wide', 'wide'), ('medium', 'medium'), ('narrow', 'narrow')], max_length=25)),
                ('martial', models.CharField(choices=[('Leather', 'Leather'), ('Rubber', 'Rubber'), ('Textiles', 'Textiles'), ('Synthetics', 'Synthetics'), ('Foam', 'Foam')], max_length=25)),
                ('style', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1000)),
                ('manufacturer', models.TextField(max_length=1000)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WomenProduct_Brand', to='Men_Products.brand')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='WomenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40')], max_length=50)),
                ('Women_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_WomenSize', to='WomenProducts.womenproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WomenImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Women_Images')),
                ('Women_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_WomenImage', to='WomenProducts.womenproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WomenColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Cream', 'Cream'), ('Brown', 'Brown')], max_length=50)),
                ('Women_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_WomenColor', to='WomenProducts.womenproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Women_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('review', models.TextField(max_length=500)),
                ('Women_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_WomenReview', to='WomenProducts.womenproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_WomenReview', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
